version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: dependencies
    open-pull-requests-limit: 5
    reviewers: 
     - XoseRamon
     - m-timmermann
     - rwenz3l
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - XoseRamon
      - rwenz3l